"""Tests for P2 fitting: round-trip recovery, log-τ, AICc convention, selection, override."""

from __future__ import annotations

import warnings

import numpy as np
import pytest

from dielectric.fitting import (
    ModelSelectionWarning,
    fit_cole_cole,
    fit_cole_cole_conductivity,
    fit_debye,
    select_model,
)
from dielectric.fitting.engine import fit
from dielectric.models.cole_cole import ColeCole
from dielectric.models.debye import Debye
from dielectric.models.multipole import MultiPoleRelaxation
from dielectric.spectrum import Spectrum

F = np.geomspace(2e8, 2e10, 101)


def test_debye_roundtrip_recovers_log_tau() -> None:
    """The memory gotcha: τ must be recovered exactly on noise-free data via log-scaling."""
    truth = Debye(5.0, 70.0, 8e-12)
    s = Spectrum(F, truth.epsilon(F))
    r = fit_debye(s)
    assert r.r_squared > 1 - 1e-9
    assert r.params["tau"] == pytest.approx(8e-12, rel=1e-4)
    assert "tau" in r.log_scaled_params


def test_cole_cole_roundtrip() -> None:
    truth = ColeCole(5.0, 70.0, 8e-12, 0.12)
    s = Spectrum(F, truth.epsilon(F))
    r = fit_cole_cole(s)
    assert r.params["alpha"] == pytest.approx(0.12, abs=1e-3)
    assert r.params["tau"] == pytest.approx(8e-12, rel=1e-3)


def test_conductivity_recovered() -> None:
    truth = MultiPoleRelaxation(5.0, ((70.0, 8e-12, 0.1),), sigma_dc=0.7)
    s = Spectrum(F, truth.epsilon(F))
    r = fit_cole_cole_conductivity(s)
    assert r.params["sigma_dc"] == pytest.approx(0.7, rel=1e-3)


def test_aicc_uses_two_times_nfreq() -> None:
    truth = ColeCole(5.0, 70.0, 8e-12, 0.1)
    s = Spectrum(F, truth.epsilon(F))
    r = fit_cole_cole(s)
    assert r.n_data == 2 * F.size  # stacked real/imag residuals


def test_weighted_fit_uses_sem() -> None:
    truth = ColeCole(5.0, 70.0, 8e-12, 0.1)
    sem = np.full(F.size, 0.05 + 0.05j)
    s = Spectrum(F, truth.epsilon(F), sem=sem)
    r = fit_cole_cole(s)
    assert r.weighted
    # reduced χ² should be ≈ small for a perfect noise-free fit weighted by σ
    assert r.chi2_reduced < 1.0


def test_uncertainties_present_and_finite() -> None:
    rng = np.random.default_rng(0)
    truth = ColeCole(5.0, 70.0, 8e-12, 0.1)
    eps = truth.epsilon(F) + rng.normal(0, 0.05, F.size) + 1j * rng.normal(0, 0.05, F.size)
    r = fit_cole_cole(Spectrum(F, eps))
    for name in r.model.param_names:
        assert np.isfinite(r.param_uncertainties[name])
        assert r.param_uncertainties[name] >= 0


def _h02_like() -> Spectrum:
    truth = MultiPoleRelaxation(5.0, ((52.0, 8e-12, 0.05),), sigma_dc=0.7)
    rng = np.random.default_rng(1)
    eps = truth.epsilon(F) + rng.normal(0, 0.02, F.size) + 1j * rng.normal(0, 0.02, F.size)
    return Spectrum(F, eps)


def test_selection_picks_cole_cole_conductivity() -> None:
    sel = select_model(_h02_like())
    assert sel.recommended.label == "Cole-Cole + DC σ"
    assert sel.chosen.label == "Cole-Cole + DC σ"
    assert not sel.overridden


def test_selection_parsimony_penalizes_extra_poles() -> None:
    sel = select_model(_h02_like())
    cc = next(rf for rf in sel.ranking if rf.label == "Cole-Cole + DC σ")
    mp2 = next(rf for rf in sel.ranking if rf.label == "MultiPole(N=2) + DC σ")
    # extra poles do not improve AICc on data generated by a single pole
    assert mp2.delta_aicc > cc.delta_aicc


def test_override_model_warns_and_is_chosen() -> None:
    with pytest.warns(ModelSelectionWarning):
        sel = select_model(_h02_like(), force_model="Havriliak-Negami")
    assert sel.chosen.label == "Havriliak-Negami"
    assert sel.overridden


def test_override_n_poles() -> None:
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        sel = select_model(_h02_like(), n_poles=2)
    assert sel.chosen.label == "MultiPole(N=2) + DC σ"


def test_override_unknown_label_raises() -> None:
    with pytest.raises(ValueError, match="not among the candidates"):
        select_model(_h02_like(), force_model="Nonexistent")


def test_generic_fit_accepts_explicit_p0() -> None:
    truth = Debye(5.0, 70.0, 8e-12)
    s = Spectrum(F, truth.epsilon(F))
    r = fit(s, Debye(4.0, 60.0, 1e-11), p0={"eps_inf": 4.5}, multistart=0)
    assert r.success
