"""Tests for P2 fitting: round-trip recovery, log-τ, AICc convention, selection, override."""

from __future__ import annotations

import warnings

import numpy as np
import pytest

from dielectric.fitting import (
    ModelSelectionWarning,
    compose_fitter,
    default_candidates,
    fit_cole_cole,
    fit_cole_cole_conductivity,
    fit_debye,
    model_info,
    model_label,
    parse_model_label,
    select_model,
)
from dielectric.fitting.engine import fit
from dielectric.models.cole_cole import ColeCole
from dielectric.models.debye import Debye
from dielectric.models.multipole import MultiPoleRelaxation
from dielectric.spectrum import Spectrum

F = np.geomspace(2e8, 2e10, 101)


def test_standardized_residuals_sum_to_chi2() -> None:
    """Pulls (residual ÷ per-point σ) must satisfy Σ|pull|² == χ² for a weighted fit."""
    truth = MultiPoleRelaxation(5.0, ((52.0, 8e-12, 0.05),), sigma_dc=0.7)
    rng = np.random.default_rng(0)
    base = truth.epsilon(F)
    reps = tuple(
        Spectrum(F, base + rng.normal(0, 0.05, F.size) + 1j * rng.normal(0, 0.05, F.size))
        for _ in range(10)
    )
    from dielectric.uncertainty import combine_repeats

    fit_res = fit_cole_cole_conductivity(combine_repeats(reps).mean)
    assert fit_res.weighted and fit_res.sigma_used is not None
    sr = fit_res.standardized_residuals
    ssq = float(np.sum(np.real(sr) ** 2) + np.sum(np.imag(sr) ** 2))
    assert ssq == pytest.approx(fit_res.chi2, rel=1e-9)


def test_unweighted_fit_has_no_sigma_used() -> None:
    truth = Debye(5.0, 70.0, 8e-12)
    r = fit(Spectrum(F, truth.epsilon(F)), Debye(4.0, 60.0, 5e-12), weighted=False)
    assert r.sigma_used is None
    assert np.allclose(r.standardized_residuals, r.residuals)  # falls back to raw


def test_debye_roundtrip_recovers_log_tau() -> None:
    """The memory gotcha: τ must be recovered exactly on noise-free data via log-scaling."""
    truth = Debye(5.0, 70.0, 8e-12)
    s = Spectrum(F, truth.epsilon(F))
    r = fit_debye(s)
    assert r.r_squared > 1 - 1e-9
    assert r.params["tau"] == pytest.approx(8e-12, rel=1e-4)
    assert "tau" in r.log_scaled_params


def test_cole_cole_roundtrip() -> None:
    truth = ColeCole(5.0, 70.0, 8e-12, 0.12)
    s = Spectrum(F, truth.epsilon(F))
    r = fit_cole_cole(s)
    assert r.params["alpha"] == pytest.approx(0.12, abs=1e-3)
    assert r.params["tau"] == pytest.approx(8e-12, rel=1e-3)


def test_conductivity_recovered() -> None:
    truth = MultiPoleRelaxation(5.0, ((70.0, 8e-12, 0.1),), sigma_dc=0.7)
    s = Spectrum(F, truth.epsilon(F))
    r = fit_cole_cole_conductivity(s)
    assert r.params["sigma_dc"] == pytest.approx(0.7, rel=1e-3)


def test_aicc_uses_two_times_nfreq() -> None:
    truth = ColeCole(5.0, 70.0, 8e-12, 0.1)
    s = Spectrum(F, truth.epsilon(F))
    r = fit_cole_cole(s)
    assert r.n_data == 2 * F.size  # stacked real/imag residuals


def test_weighted_fit_uses_sem() -> None:
    truth = ColeCole(5.0, 70.0, 8e-12, 0.1)
    sem = np.full(F.size, 0.05 + 0.05j)
    s = Spectrum(F, truth.epsilon(F), sem=sem)
    r = fit_cole_cole(s)
    assert r.weighted
    # reduced χ² should be ≈ small for a perfect noise-free fit weighted by σ
    assert r.chi2_reduced < 1.0


def test_uncertainties_present_and_finite() -> None:
    rng = np.random.default_rng(0)
    truth = ColeCole(5.0, 70.0, 8e-12, 0.1)
    eps = truth.epsilon(F) + rng.normal(0, 0.05, F.size) + 1j * rng.normal(0, 0.05, F.size)
    r = fit_cole_cole(Spectrum(F, eps))
    for name in r.model.param_names:
        assert np.isfinite(r.param_uncertainties[name])
        assert r.param_uncertainties[name] >= 0


def _h02_like() -> Spectrum:
    truth = MultiPoleRelaxation(5.0, ((52.0, 8e-12, 0.05),), sigma_dc=0.7)
    rng = np.random.default_rng(1)
    eps = truth.epsilon(F) + rng.normal(0, 0.02, F.size) + 1j * rng.normal(0, 0.02, F.size)
    return Spectrum(F, eps)


def test_selection_picks_cole_cole_conductivity() -> None:
    sel = select_model(_h02_like())
    assert sel.recommended.label == "Cole-Cole + DC σ"
    assert sel.chosen.label == "Cole-Cole + DC σ"
    assert not sel.overridden


def test_selection_parsimony_penalizes_extra_poles() -> None:
    sel = select_model(_h02_like())
    cc1 = next(rf for rf in sel.ranking if rf.label == "Cole-Cole + DC σ")
    cc2 = next(rf for rf in sel.ranking if rf.label == "Cole-Cole (2 poles) + DC σ")
    # extra poles do not improve AICc on data generated by a single pole
    assert cc2.delta_aicc > cc1.delta_aicc


def test_override_model_warns_and_is_chosen() -> None:
    with pytest.warns(ModelSelectionWarning):
        sel = select_model(_h02_like(), force_model="Havriliak-Negami")
    assert sel.chosen.label == "Havriliak-Negami"
    assert sel.overridden


def test_override_n_poles() -> None:
    # auto + a pole count is a panel constraint (ladders Debye/Cole-Cole), not an override.
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        sel = select_model(_h02_like(), n_poles=2)
    assert "(2 poles)" in sel.chosen.label
    assert not sel.overridden
    assert any("constrained" in w for w in sel.warnings)


def test_override_unknown_label_raises() -> None:
    with pytest.raises(ValueError, match="unknown model family"):
        select_model(_h02_like(), force_model="Nonexistent")


def test_legacy_multipole_label_rejected_with_help() -> None:
    with pytest.raises(ValueError, match="old naming"):
        select_model(_h02_like(), force_model="MultiPole(N=2) + DC σ")


def test_unknown_label_error_lists_candidates() -> None:
    with pytest.raises(ValueError) as exc:
        select_model(_h02_like(), force_model="Nonexistent")
    msg = str(exc.value)
    assert "available: " in msg
    assert "Cole-Cole" in msg
    assert "['" not in msg  # human-readable list, not a Python repr


def test_n_poles_out_of_range_raises() -> None:
    for bad in (0, 7, -1):
        with pytest.raises(ValueError, match="n_poles must be between"):
            select_model(_h02_like(), n_poles=bad)


def test_dc_sigma_constrains_candidate_panel() -> None:
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        with_dc = select_model(_h02_like(), dc_sigma=True)
        without_dc = select_model(_h02_like(), dc_sigma=False)
    assert all("DC σ" in rf.label for rf in with_dc.ranking)
    assert "DC σ" in with_dc.chosen.label
    assert not with_dc.overridden  # a panel constraint, not a forced model
    assert all("DC σ" not in rf.label for rf in without_dc.ranking)
    # the constraint is disclosed
    assert any("constrained" in w for w in without_dc.warnings)


def test_dc_sigma_composes_with_forced_family() -> None:
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        on = select_model(_h02_like(), force_model="Debye", dc_sigma=True)
        off = select_model(_h02_like(), force_model="Cole-Cole", dc_sigma=False)
    assert on.chosen.label == "Debye + DC σ"  # the DC term composes with the forced family
    assert off.chosen.label == "Cole-Cole"
    assert on.overridden and off.overridden


def test_force_dc_or_poles_on_nonladder_family_raises() -> None:
    for kwargs in ({"n_poles": 2}, {"dc_sigma": True}):
        with pytest.raises(ValueError, match=r"Debye|Cole-Cole"):
            select_model(_h02_like(), force_model="Havriliak-Negami", **kwargs)  # type: ignore[arg-type]


def test_weighted_misfit_flags_chi2_and_optimistic_uncertainties() -> None:
    # weighted data from a 1-pole + DC σ truth, forced into a plain Debye → gross misfit
    s = _h02_like()
    sem = np.full(F.size, 0.02) * (1 + 1j)
    weighted = Spectrum(F, s.epsilon, sem=sem)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        sel = select_model(weighted, force_model="Debye")
    assert sel.chosen.result.chi2_reduced > 5
    assert any("optimistic" in w for w in sel.warnings)


def test_degenerate_fit_not_recommended() -> None:
    """A lower-AICc fit whose parameters are unidentifiable must not be recommended."""
    from dielectric.io import MeasurementSet

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        ms = MeasurementSet.from_glob("data/h02s19m*.csv")
        sel = select_model(ms.type_a().mean)
    # The free-α Cole-Cole multipoles have lower AICc but collapse σ (degenerate); the recommended
    # model must itself be identifiable, even though degenerate candidates outrank it on AICc.
    assert not sel.recommended.degenerate
    assert "DC σ" in sel.recommended.label
    assert any(
        rf.degenerate and rf.result.aicc < sel.recommended.result.aicc for rf in sel.ranking
    )


def test_small_sample_stays_in_family_not_worse_model() -> None:
    """With few repeats the recommendation must stay a conductivity model, never a qualitatively
    worse fit (e.g. Jonscher). The pinned-α Debye ladder keeps it identifiable here."""
    import glob

    from dielectric.io.campaign import MeasurementSet
    from dielectric.io.csv_loader import load_agilent_85070

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        paths = sorted(glob.glob("data/h02s19m*.csv"))[:5]
        ms = MeasurementSet("s", tuple(load_agilent_85070(p) for p in paths), 25.0)
        sel = select_model(ms.type_a().mean)
    assert "DC σ" in sel.recommended.label  # still the conductive family, not Jonscher/plain Debye
    assert not sel.recommended.degenerate  # the Debye ladder gives an identifiable fit


def test_generic_fit_accepts_explicit_p0() -> None:
    truth = Debye(5.0, 70.0, 8e-12)
    s = Spectrum(F, truth.epsilon(F))
    r = fit(s, Debye(4.0, 60.0, 1e-11), p0={"eps_inf": 4.5}, multistart=0)
    assert r.success


# -- compositional grammar -----------------------------------------------------------------------


def test_default_panel_is_eleven_and_grammar_round_trips() -> None:
    labels = list(default_candidates(3))
    assert len(labels) == 11
    assert "Debye (3 poles) + DC σ" in labels
    assert "Cole-Cole (2 poles) + DC σ" in labels
    assert not any("MultiPole" in label for label in labels)
    for label in [*labels, "Debye (5 poles) + DC σ"]:
        family, n, dc = parse_model_label(label)
        assert model_label(family, n, dc) == label


def test_compose_fitter_rejects_invalid_combinations() -> None:
    for family in ("Cole-Davidson", "Havriliak-Negami", "Jonscher"):
        with pytest.raises(ValueError, match=r"Debye|Cole-Cole"):
            compose_fitter(family, n_poles=2)
        with pytest.raises(ValueError, match=r"Debye|Cole-Cole"):
            compose_fitter(family, dc_sigma=True)
    with pytest.raises(ValueError, match="unknown model family"):
        compose_fitter("Nope")
    with pytest.raises(ValueError, match="n_poles must be"):
        compose_fitter("Debye", n_poles=0)


def test_model_info_covers_panel_with_equations() -> None:
    for label in default_candidates(3):
        info = model_info(label)
        assert info.equation.startswith("ε* = ε∞")
        assert info.description
        if label.endswith("+ DC σ"):
            assert "σ_dc" in info.equation
            assert "DC-conductivity" in info.description


# -- the pinned-α Debye ladder -------------------------------------------------------------------


def test_fixed_alpha_excludes_alpha_and_keeps_pinned_value() -> None:
    terms = ((50.0, 8e-12, 0.0), (5.0, 1e-10, 0.0))
    m = MultiPoleRelaxation(5.0, terms, sigma_dc=0.7, fixed_alpha=True)
    assert "alpha_1" not in m.param_names and "alpha_2" not in m.param_names
    assert m.param_names == ("eps_inf", "delta_eps_1", "tau_1", "delta_eps_2", "tau_2", "sigma_dc")
    # with_params updates Δε/τ/σ but leaves the pinned α untouched
    updated = m.with_params({"delta_eps_1": 60.0, "tau_1": 9e-12})
    assert updated.terms[0] == (60.0, 9e-12, 0.0)


def test_debye_ladder_provenance_cites_debye() -> None:
    label, fn = compose_fitter("Debye", n_poles=2, dc_sigma=True)
    assert label == "Debye (2 poles) + DC σ"
    truth = MultiPoleRelaxation(
        4.0, ((40.0, 8e-12, 0.0), (8.0, 1.5e-10, 0.0)), sigma_dc=0.5, fixed_alpha=True
    )
    s = Spectrum(F, truth.epsilon(F))
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        res = fn(s)
    assert "Debye" in res.model.provenance.authors
    # a 2-Debye-pole + σ truth is recovered well
    assert res.r_squared > 0.999


def test_auto_picks_debye_ladder_on_debye_truth() -> None:
    truth = MultiPoleRelaxation(
        4.0, ((40.0, 7e-12, 0.0), (10.0, 2e-10, 0.0)), sigma_dc=0.6, fixed_alpha=True
    )
    rng = np.random.default_rng(3)
    eps = truth.epsilon(F) + rng.normal(0, 0.02, F.size) + 1j * rng.normal(0, 0.02, F.size)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        sel = select_model(Spectrum(F, eps))
    assert sel.recommended.label.startswith("Debye")
    assert "DC σ" in sel.recommended.label


# -- riding features: rationale, per-component metrics, band-edge ---------------------------------


def test_selection_rationale_and_excluded_reasons_populated() -> None:
    sel = select_model(_h02_like())
    assert sel.recommended.label in sel.rationale
    assert sel.recommended.excluded_reason == ""
    assert all(rf.excluded_reason for rf in sel.ranking if rf.label != sel.recommended.label)


def test_per_component_msp_consistent_with_chi2() -> None:
    # weighted fit → mean of (msp_real, msp_imag) ≈ χ² / N  (Σ pull² = χ², N = 2·n_freq)
    truth = MultiPoleRelaxation(5.0, ((52.0, 8e-12, 0.05),), sigma_dc=0.7)
    rng = np.random.default_rng(0)
    base = truth.epsilon(F)
    reps = [base + rng.normal(0, 0.05, F.size) + 1j * rng.normal(0, 0.05, F.size) for _ in range(8)]
    from dielectric.uncertainty.typea import combine_repeats

    ta = combine_repeats(tuple(Spectrum(F, r) for r in reps))
    res = fit_cole_cole_conductivity(ta.mean)
    assert np.isfinite(res.msp_real) and np.isfinite(res.msp_imag)
    assert (res.msp_real + res.msp_imag) / 2.0 == pytest.approx(res.chi2 / res.n_data, rel=1e-6)


def test_unweighted_r2_component_may_be_negative() -> None:
    # plain Debye on a conductive spectrum misfits ε'' badly → its component R² is the worse one
    s = _h02_like()
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        res = fit_debye(s)
    assert np.isfinite(res.r_squared_imag)
    assert res.r_squared_imag < res.r_squared_real  # ε'' is the worse-fit component


def test_band_edge_pole_warning() -> None:
    # a pole forced far below the measured band should trip the band-edge disclosure
    s = _h02_like()  # band 0.2–20 GHz
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        sel = select_model(s, force_model="Cole-Cole (2 poles) + DC σ")
    f_peaks = [
        1.0 / (2.0 * np.pi * v) for k, v in sel.chosen.result.params.items() if k.startswith("tau")
    ]
    out_of_band = any(fp < 0.2e9 or fp > 20e9 for fp in f_peaks)
    has_warning = any("outside the measured band" in w for w in sel.warnings)
    assert has_warning == out_of_band
