function run_tests()
%RUN_TESTS  Cross-check the MATLAB/Octave port against the Python reference values.
%
%   The expected values below were produced by the Python `dielectric` evaluator for
%   MultiPoleRelaxation(eps_inf=5, terms=((52, 8e-12, 0.1),), sigma_dc=0.7). If this passes, the
%   MATLAB port is numerically identical to the validated Python core. Run: octave run_tests.m

  f = [2e8; 1e9; 5e9; 2e10];
  expected = [ ...
     56.858016, -63.726489; ...
     56.229526, -15.976496; ...
     51.310630, -15.144748; ...
     30.892846, -22.835008];

  eps = cole_cole(f, 5.0, 52.0, 8e-12, 0.1, 0.7);
  err = max(abs(eps - (expected(:,1) + 1i*expected(:,2))));
  fprintf('cole_cole max |error| vs Python reference: %.2e\n', err);
  assert(err < 1e-4, 'cole_cole disagrees with the Python reference');

  % Round-trip: fit noise-free data generated by the model and recover the parameters.
  eps_syn = cole_cole(f, 5.0, 52.0, 8e-12, 0.1, 0.7);
  fdense = logspace(log10(2e8), log10(2e10), 101)';
  eps_dense = cole_cole(fdense, 5.0, 52.0, 8e-12, 0.1, 0.7);
  [p, gof] = fit_cole_cole(fdense, eps_dense);
  fprintf('fit R^2 = %.6f, recovered tau = %.3e (truth 8e-12), sigma = %.3f (truth 0.7)\n', ...
          gof.r2, p.tau, p.sigma_dc);
  assert(gof.r2 > 0.999, 'fit did not converge');

  fprintf('All MATLAB/Octave port checks passed.\n');
end
