"""Render a :class:`ReportData` to a single self-contained HTML file.

No optional dependencies: figures are base64-embedded and the CSS is inline, so the file opens in
any browser offline and is convenient to copy figures/tables from into a manuscript. Mirrors the
content of the PDF/Word renderers so the three outputs never drift.
"""

from __future__ import annotations

import base64
import html
from pathlib import Path

from .report import ReportData


def _embed_figure(fig_path: str) -> str:
    p = Path(fig_path)
    if not p.exists():
        return ""
    data = base64.b64encode(p.read_bytes()).decode("ascii")
    suffix = p.suffix.lstrip(".").lower() or "png"
    mime = "image/svg+xml" if suffix == "svg" else f"image/{suffix}"
    alt = html.escape(p.stem)
    return f'<img class="fig" src="data:{mime};base64,{data}" alt="{alt}" />'


_CSS = """
:root { color-scheme: light; }
body { font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
       max-width: 880px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; }
h1 { font-size: 1.7rem; margin-bottom: .2rem; }
h2 { font-size: 1.15rem; margin-top: 1.8rem; border-bottom: 1px solid #e5e5e5;
     padding-bottom: .2rem; }
.status { font-weight: 600; padding: .5rem .75rem; border-radius: 6px; display: inline-block; }
.status.ok { background: #e7f6ec; color: #14633a; }
.status.warn { background: #fcefe7; color: #9a3b12; }
table { border-collapse: collapse; margin: .5rem 0; }
td, th { padding: .25rem .75rem; border-bottom: 1px solid #eee; text-align: left; }
td.num { font-variant-numeric: tabular-nums; }
pre { background: #f6f8fa; border: 1px solid #e5e7eb; border-radius: 6px; padding: .75rem;
      overflow-x: auto; font: 12px/1.4 ui-monospace, "SF Mono", Menlo, monospace; }
.fig { max-width: 100%; margin: .75rem 0; border: 1px solid #eee; border-radius: 6px; }
.notes li { margin: .2rem 0; }
footer { margin-top: 2.5rem; color: #888; font-size: .85rem; border-top: 1px solid #eee;
         padding-top: .75rem; }
"""

_FOOTER = "Generated by the dielectric toolkit — self-contained report, safe to archive offline."


def _param_table(report: ReportData) -> str:
    rows = "".join(
        f"<tr><td>{html.escape(name)}</td><td class='num'>{html.escape(value)}</td></tr>"
        for name, value in (*report.parameter_rows, *report.gof_rows)
    )
    return f"<table><tbody>{rows}</tbody></table>"


def html_document(title: str, body: str) -> str:
    """Wrap inner ``body`` HTML in a self-contained document (shared CSS + footer)."""
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>{html.escape(title)}</title>
<style>{_CSS}</style>
</head>
<body>
{body}
<footer>{html.escape(_FOOTER)}</footer>
</body>
</html>
"""


def report_body_html(report: ReportData, *, title_tag: str = "h1") -> str:
    """The per-report content (heading + sections), reusable inside a combined document."""
    validated = report.validation_status.strip().upper().startswith("VALIDATED")
    status_cls = "ok" if validated else "warn"
    figures = "".join(_embed_figure(fp) for fp in report.figure_paths)
    notes = "".join(f"<li>{html.escape(n)}</li>" for n in report.extra_notes)
    notes_block = f"<ul class='notes'>{notes}</ul>" if notes else ""
    return f"""<{title_tag}>{html.escape(report.title)}</{title_tag}>
<p><span class="status {status_cls}">{html.escape(report.validation_status)}</span></p>

<h2>Methods</h2>
<p>{html.escape(report.methods)}</p>

<h2>Fitted parameters</h2>
{_param_table(report)}

<h2>Model selection</h2>
<pre>{html.escape(report.selection_table)}</pre>
{notes_block}

<h2>Figures</h2>
{figures or "<p>(no figures)</p>"}

<h2>References (BibTeX)</h2>
<pre>{html.escape(report.bibtex)}</pre>

<h2>Reproducibility manifest</h2>
<pre>{html.escape(report.manifest_json)}</pre>
"""


def render_html(report: ReportData, path: str | Path) -> None:
    """Write ``report`` as one self-contained HTML file."""
    Path(path).write_text(html_document(report.title, report_body_html(report)), encoding="utf-8")
